import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



import { Keania_One } from 'next/font/google';

const keaniaOne = Keania_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-keania',
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={keaniaOne.variable}
      >
        {children}
      </body>
    </html>
  );
}
